import { Check, IdCard, ShieldCheck, UserRound } from 'lucide-react'
import { Text } from '@/components/atoms'
import { PublicCertifiedCopyFrame } from '@/components/organisms/public-certified-copy-frame'
import type { DetailRowProps, ValidCertifiedCopyProps } from './types'

function DetailRow({
  icon,
  label,
  value,
  isLast,
}: Readonly<DetailRowProps>) {
  return (
    <div
      className={[
        'flex items-center gap-5 px-5 py-4 sm:px-6 sm:py-5',
        !isLast && 'border-b border-[#e5e7eb]',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-[#e8f4ed] text-[#08784f]">
        {icon}
      </div>
      <div className="min-w-0 text-left">
        <Text
          as="p"
          variant="caption"
          className="uppercase text-[#526068]"
        >
          {label}
        </Text>
        <Text
          as="p"
          variant="sub-md"
          className="mt-1 truncate text-xl font-bold text-[#111827] sm:text-2xl"
        >
          {value}
        </Text>
      </div>
    </div>
  )
}
export function ValidCertifiedCopy({
  citizenName = 'Kayla Patel',
  maskedId = '9000 ••••••• 000',
}: Readonly<ValidCertifiedCopyProps>) {
  return (
    <PublicCertifiedCopyFrame>
      <div
        aria-live="polite"
        className="w-full max-w-2xl rounded-[24px] border border-[#4c7467] bg-white/90 px-5 py-8 shadow-[0_18px_50px_rgba(5,59,44,0.08)] backdrop-blur-sm sm:px-12 sm:py-12"
      >
        <div className="flex flex-col items-center text-center">
          <div className="flex h-28 w-28 items-center justify-center rounded-full bg-[#e7f5ed] sm:h-32 sm:w-32">
            <div className="flex h-20 w-20 items-center justify-center rounded-full bg-[#0da463] text-white sm:h-24 sm:w-24">
              <Check className="h-12 w-12 sm:h-14 sm:w-14" strokeWidth={3} />
            </div>
          </div>
          <Text
            as="h1"
            variant="h1"
            className="mt-8 text-3xl text-[#053b2c] sm:text-4xl"
          >
            Certified Copy Valid
          </Text>
          <Text
            as="p"
            variant="sub-md"
            className="mt-4 max-w-lg text-[#34434b]"
          >
            This certified copy was generated by FlashID and is currently
            valid.
          </Text>
        </div>
        <div className="my-8 h-px bg-[#e5e7eb]" />
        <div className="overflow-hidden rounded-2xl border border-[#e5e7eb]">
          <DetailRow
            icon={<UserRound className="h-7 w-7" />}
            label="Citizen name"
            value={citizenName}
          />
          <DetailRow
            icon={<IdCard className="h-7 w-7" />}
            label="ID number"
            value={maskedId}
            isLast
          />
        </div>
        <div className="mt-8 flex items-start gap-4 border-t border-[#e5e7eb] pt-7">
          <ShieldCheck className="mt-0.5 h-8 w-8 shrink-0 text-[#08784f]" />
          <Text
            as="p"
            variant="sub-sm"
            className="text-[#34434b] sm:text-base"
          >
            This verification confirms the certification record and current
            status of the source credential.
          </Text>
        </div>
      </div>
    </PublicCertifiedCopyFrame>
  )
}