import type { ReactNode } from 'react'
import { render, screen } from '@testing-library/react'
import { ValidCertifiedCopy } from '../valid-certified-copy'

jest.mock('@/components/organisms/public-certified-copy-frame', () => ({
  PublicCertifiedCopyFrame: ({ children }: { children: ReactNode }) => (
    <>{children}</>
  ),
}))
describe('ValidCertifiedCopy', () => {
  it('renders the valid certified-copy state', () => {
    render(<ValidCertifiedCopy />)
    expect(
      screen.getByRole('heading', { name: 'Certified Copy Valid' })
    ).toBeInTheDocument()

    expect(
      screen.getByText(
        'This certified copy was generated by FlashID and is currently valid.'
      )
    ).toBeInTheDocument()
  })
  it('renders the default citizen details', () => {
    render(<ValidCertifiedCopy />)
    expect(screen.getByText('Kayla Patel')).toBeInTheDocument()
    expect(screen.getByText('9000 ••••••• 000')).toBeInTheDocument()
    expect(screen.getByText('Citizen name')).toBeInTheDocument()
    expect(screen.getByText('ID number')).toBeInTheDocument()
  })
  it('renders custom citizen details', () => {
    render(
      <ValidCertifiedCopy
        citizenName="Thabo Mokoena"
        maskedId="8000 ••••••• 111"
      />
    )
    expect(screen.getByText('Thabo Mokoena')).toBeInTheDocument()
    expect(screen.getByText('8000 ••••••• 111')).toBeInTheDocument()
  })
  it('renders the verification explanation', () => {
    render(<ValidCertifiedCopy />)
    expect(
      screen.getByText(
        'This verification confirms the certification record and current status of the source credential.'
      )
    ).toBeInTheDocument()
  })
})
