<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Azure.Communication.Sms" Version="1.1.0-beta.3" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.1" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
        <PackageReference Include="MimeKit" Version="4.17.0" />
        <PackageReference Include="NSec.Cryptography" Version="26.4.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="tests" />
    </ItemGroup>

</Project>
