openapi: 3.0.4
info:
  title: Presentation
  version: '1.0'
paths:
  /api/citizens/{saId}:
    get:
      tags:
      - CitizenRecord
      parameters:
      - name: saId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
  /api/credentials/{saId}/identity-document:
    get:
      tags:
      - Credentials
      parameters:
      - name: saId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
  /api/credentials/{saId}/drivers-license:
    get:
      tags:
      - Credentials
      parameters:
      - name: saId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
components: {}
tags:
- name: CitizenRecord
- name: Credentials
