name: Build and deploy web app to Azure Web App - web-flashid-dev

on: 
  push:
    branches: 
      - dev
      - fix/stuck-on-login-page
    paths:
      - "web/**"
      - "pnpm-lock.yaml"
      - "dockerfile.web"
      - ".github/workflows/dev_web-flashid-dev.yml"
  workflow_dispatch:

env:
  ACR_NAME: acrflashid
  IMAGE_NAME: web-flashid

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/fix/stuck-on-login-page'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push dev image
        run: |
          docker build -f dockerfile.web \
            --build-arg NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL_DEV }} \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:dev-${{ github.sha }} \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:dev-latest \
            .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:dev-latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3
        with:
          app-name: 'web-flashid-dev'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB_DEV }}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:dev-${{ github.sha }}'

# for future version bumps:
# git ls-remote https://github.com/docker/login-action v3
# git ls-remote https://github.com/azure/webapps-deploy v3
