using Application.Common.Interfaces.ProviderInterfaces;
using Application.Features.CertifiedCredentialCopies.Models;
using QRCoder;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace Infrastructure.Providers;

public class CertifiedCopyPdfProvider : ICertifiedCopyPdfProvider
{
    public byte[] Generate(CertifiedCredentialSnapshot snapshot, Guid certificationId, string verificationUrl,
        DateTime generatedAt, byte[]? photoBytes = null)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        ArgumentException.ThrowIfNullOrWhiteSpace(verificationUrl);

        var qrCodeBytes = GenerateQrCode(verificationUrl);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);

                page.Header().Text("FLASH ID").Bold().FontSize(20);

                page.Content().PaddingVertical(20).Column(column =>
                    {
                        column.Spacing(10);

                        column.Item().Text("CERTIFIED DIGITAL CREDENTIAL").Bold().FontSize(18);

                        column.Item().Text(snapshot.CredentialType);

                        column.Item().Text($"Name: {snapshot.FullName}");

                        column.Item().Text($"ID Number: {snapshot.IdNumber}");

                        column.Item().Text($"Issued by: {snapshot.IssuedBy}");

                        column.Item().Text($"Generated: {generatedAt:dd MMMM yyyy HH:mm} UTC");

                        column.Item().Text($"Certification ID: {certificationId}");

                        if (photoBytes is { Length: > 0 })
                        {
                            column.Item().Width(120).Image(photoBytes);
                        }

                        column.Item().PaddingTop(15).Text("Verify this certified copy").Bold();

                        column.Item().Width(120).Height(120).Image(qrCodeBytes);

                        column.Item().Text(verificationUrl).FontSize(8);
                    });

                page.Footer().AlignCenter().Text("Generated by FlashID");
            });
        });

        return document.GeneratePdf();
    }

    private static byte[] GenerateQrCode(string verificationUrl)
    {
        using var qrGenerator = new QRCodeGenerator();

        using var qrData = qrGenerator.CreateQrCode(
            verificationUrl,
            QRCodeGenerator.ECCLevel.Q);

        var qrCode = new PngByteQRCode(qrData);

        return qrCode.GetGraphic(20);
    }
}